terminate called after throwing an instance of 'std::length_error'
  what():  cannot create std::vector larger than max_size()
======== Error: Application received signal 6
srun: error: r18g03: task 0: Exited with exit code 15
srun: Terminating StepId=22022134.0

real	0m0.345s
user	0m0.011s
sys	0m0.005s
